// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiAjH8q2TFqbrfturEIQKTnnqAmmEzQXQ',
    appId: '1:664574495771:web:8505448b18e2c0d15c3cbe',
    messagingSenderId: '664574495771',
    projectId: 'sports-buddy-88470',
    authDomain: 'sports-buddy-88470.firebaseapp.com',
    storageBucket: 'sports-buddy-88470.appspot.com',
    measurementId: 'G-RS2K7RFD2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGwgIwoGz1B87r8G6jcNW8Jws3bU6sOxY',
    appId: '1:664574495771:android:ea32f5982a005ba65c3cbe',
    messagingSenderId: '664574495771',
    projectId: 'sports-buddy-88470',
    storageBucket: 'sports-buddy-88470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC77sYT-FbGxNduLfJ88t2BAKzzCaKKJ_4',
    appId: '1:664574495771:ios:7bd2fc5eb0de43795c3cbe',
    messagingSenderId: '664574495771',
    projectId: 'sports-buddy-88470',
    storageBucket: 'sports-buddy-88470.appspot.com',
    iosClientId: '664574495771-cr8tq9h6ce5bim6p8vjn8pf3ubg6j61b.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminDashboard',
  );
}
